category/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('category/', include('categories.urls')),
    
]

urls.py
from django.urls import path
from . import views

app_name = 'categories'
urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.new_category, name='add'),
    path('<int:pk>/', views.detail_category, name='detail'),
    path('edit/<int:pk>/', views.edit_category, name='edit'),
    path('delete/<int:pk>', views.delete_category, name='delete'),
]

models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)                                        
    state = models.BooleanField(default=True)

    def __str__(self):
        return self.name
#class Meta:
   # ordering = ('name',)
    #verbose_name = 'category'
   # verbose_name_plural = 'categories'
    
class SubCategory(models.Model):
    name = models.CharField(max_length=200,db_index=True)                                        
    state = models.BooleanField(default=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)

#class Meta:
  #  ordering = ('name',)
  #  verbose_name = 'subcategory'
  #  verbose_name_plural = 'subcategories'

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category,blank=True,default=None,on_delete=models.CASCADE)
    subcategory = models.OneToOneField(SubCategory,unique=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    #related_name='products',on_delete=models.CASCADE)
    #slug = models.SlugField(max_length=200, db_index=True)
    #description = models.TextField(blank=True)

#class Meta:
   # ordering = ('name',)
    #index_together = (('id', 'slug'),)
    

categories/forms.py
#forms.py
from django.forms import ModelForm
from .models import Category

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ('name', 'state',)

views.py
from django.shortcuts import get_object_or_404, render
from django.shortcuts import redirect

from .models import Category,SubCategory
from .forms import CategoryForm

def index(request):
    all_categories = Category.objects.all()    #retrive all categories
    context = {'all_categories': all_categories}
    return render(request, 'categories/index.html', context)


def detail_category(request, pk):
    category = get_object_or_404(Category, pk=pk)   #retrive single category
    return render(request, 'categories/detail.html', {'category': category})

#create   
def new_category(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.save()
            return redirect('categories:detail', pk=category.pk)
    else:
        form = CategoryForm()
    return render(request, 'categories/add.html', {'form': form})

#update
def edit_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            category = form.save(commit=False)
            category.save()
            return redirect('categories:detail', pk=category.pk)
    else:
        form = CategoryForm()
    return render(request, 'categories/edit.html', {'form': form})

#delete
def delete_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category.delete()
    return redirect('categories:index')

templates/categories/add.html

<h2>New Category</h2>
    <form method="POST">{% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        
        <button type="submit">Save</button>
    </form>

templates/categories/detail.html
<h2>{{ category.name }}</h2>

templates/categories/edit.html

<h2>Edit Category</h2>
    <form method="POST">{% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        
        <button type="submit">Save</button>
    </form>

templates/categories/index.html
<!DOCTYPE html>
<html>
   <head><title>index</title></head> 
   <style>
        table{
            border: 2px solid black;
            border-collapse:  collapse;
            width: 50%;
        }
        th, td {
            border: 1px solid black;
            padding: 5px;
            text-align: center;
        }
        th {
            background-color: lightgrey;
        }
   </style>
   <body>
        <h1>List of Categories</h1>
        <a href="{% url "categories:add" %}">Add</a> <br/><br/>
        <table>
            <thead>
                <tr>
                <th>Name</th>
                <th>SubCategory</th>
                <th>Edit</th>
                <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for category in all_categories %}
                <tr>
                <td>{{ category.name }}</td>
                <td><a href="{% url "categories:detail" category.id %}">View</a></td>
                <td><a href="{% url "categories:edit" category.id %}">edit</a></td>
                <td><a href="{% url "categories:delete" category.id %}">delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
            </table>      
    </body>
   </html>